ecosystem/platform/server/config/routes.rb
# frozen_string_literal: true

# Copyright (c) Aptos
# SPDX-License-Identifier: Apache-2.0

Rails.application.routes.draw do
  devise_for :users, {
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      sessions: 'users/sessions'
    }
  }
  ActiveAdmin.routes(self)

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :api do
    # get ':provider/callback', to: 'sessions#create'
    get 'users/me', to: 'users#me'
    resources :users, only: %i[show update]
  end

  namespace :user do
    root to: redirect('/it1') # creates user_root_path, where users go after confirming email
  end

  # KYC routes
  get 'onboarding/kyc_redirect', to: 'onboarding#kyc_redirect'
  get 'onboarding/kyc_callback', to: 'onboarding#kyc_callback'

  get 'onboarding/email'
  get 'onboarding/email_success'
  post 'onboarding/email', to: 'onboarding#email_update'

  get 'health', to: 'health#health'

  resources :overview, only: %i[index]
  resources :it1_profiles, except: %i[index destroy]

  get 'leaderboard/it1', to: redirect('/it1')

  get 'it1', to: 'leaderboard#it1'
  root 'welcome#index'
end

ecosystem/platform/server/app/controllers/overview_controller.rb
# frozen_string_literal: true

# Copyright (c) Aptos
# SPDX-License-Identifier: Apache-2.0

class OverviewController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_confirmed!

  def index
    redirect_to root_path
  end
end

ecosystem/platform/server/app/helpers/overview_helper.rb
# Copyright (c) Aptos
# SPDX-License-Identifier: Apache-2.0
# frozen_string_literal: true

module OverviewHelper
end

ecosystem/platform/server/app/views/overview/index.html.erb
<div class="p-6">
   <div class="flex flex-col gap-4">
     <%= render "layouts/flash" %>

    <% if current_user.confirmed_at.nil? %>
      <p class="bg-gray-100 border border-gray-400 text-gray-700 px-4 py-3 rounded">
      Your email has not yet been verified. Didn't receive a verification email? <%= render(LinkComponent.new(href: onboarding_email_path)) { "Re-send verification email" } %>
      </p>
    <% end %>

    <p class="bg-gray-100 border border-gray-400 text-gray-700 px-4 py-3 rounded">
      <% if current_user.it1_profile %>
        IT1 application received.
        <%= render(LinkComponent.new(href: edit_it1_profile_path(current_user.it1_profile))) { "Edit your application" } %>
      <% else %>
        Registration for IT1 is open!
        <%= render(LinkComponent.new(href: it1_path)) { "Apply now" } %>
      <% end %>
    </p>
  </div>
</div>